### ISSUE TITLE
Login prompt not being centered on boot

### ISSUE THREAD

**Issue by wwsmiff** [fairyglade/ly#486]
Im using arch and sway and whenever i boot/reboot the login prompt is not centered and only once i start typing in the details it gets centered. Is there a way to fix this? Also is there a way to set one WM/Desktop as the first preference?

**Comment by IlliaHalchun** [comment]
Have the same problem..

**Comment by AnErrupTion** [comment]
> and only once i start typing in the details it gets centered.

For now, I can only guess this is a termbox problem (the library Ly uses for making a TUI interface).

> Also is there a way to set one WM/Desktop as the first preference?

Ly should use the last-used entry as the default.

**Comment by Pheon-Dev** [comment]
Me too. But it only does so when multiple monitors are connected, say two. Just as the default unpatched dwm cursor positions itself when the desktop is loaded. It defaults to center of the two monitors, so does ly. The login prompt would position itself right where the cursor would have been

**Comment by RikiReal** [comment]
This issue only started appearing for me after the last update to ly in the arch repo. That was on 2023-06-15 and the version is 0.6.0-1
https://archlinux.org/packages/?name=ly

**Comment by RoccoRakete** [comment]
Same issue here

**Comment by katekyy** [comment]
Same. Started appearing in 0.6.0.

**Comment by Rider3268** [comment]
Same

**Comment by sanj0** [comment]
I have the same issue on arch with a build of the current state on master. Any updates on this issue?

**Comment by Pheon-Dev** [comment]
I'll have a look at the code and maybe make a PR if I find the solution. For now I'm using [lemurs](https://github.com/coastalwhite/lemurs) which is also a minimal login manager that has worked great for me so far

**Comment by sanj0** [comment]
In trying (and succeeding) to change the colors of ly, I've stumbled upon a workaround fix for this issue. As the box centers as soon as I type the first character of my password, the following `ExecStartPre` not only changes the colors of ly (first hex is bg, second hex is fg) but also "simulates user input" I guess and therefore automatically centers the box:

```service
# in /etc/systemd/system/display-manager.service
# ...
[Service]
# ...
ExecStartPre=/usr/bin/printf '%%b' '\e]P0DED8C9\e]P70E313A\ec'
ExecStart=/usr/bin/ly
# ...
```

**Comment by lunigella** [comment]
I had the same issue with qtile on arch and nvidia graphics card, I noticed that after installing CUDA nvidia package from the repo fixed the problem. I don't know why tho.

**Comment by StuSerious** [comment]
Same issue here with Arch master.  As others stated above, user input centers it back to normal.

**Comment by rudolflovrencic** [comment]
Same issue - user input centers it.

**Comment by cprin21** [comment]
Also getting same issue. It's rather frustrating because of the expectation of a clean TUI  environment something like ly should have. Unsure why it doesn't centre until user input is given.

**Comment by StuSerious** [comment]
@cprin21 a bit late but I have since moved to [`greetd`](https://sr.ht/~kennylevinsen/greetd/) using [`tuigreet`](https://github.com/apognu/tuigreet) and it has been a flawless (if not better) substitute ever since.

**Comment by marcocamilo** [comment]
Any updates on this? I have the same problem, but even when typing the login pane isn't centered. I'm using Arch, as display managers I have dwm and Gnome

**Comment by AnErrupTion** [comment]
@marcocamilo Do you have 2 monitors with different resolutions, by any chance?

**Comment by marcocamilo** [comment]
No, not at all. Im using it on my macbook. Do I have to set the definition somehow by default inside the tty?

Marco-Andrés Camilo-Pietri

**Comment by AnErrupTion** [comment]
Hm, then that's an odd one. You shouldn't have to set the resolution in the TTY yourself since it should just pick the highest one available.

**Comment by Tadas** [comment]
Not sure if there are several different issues here, but here's how I've gotten Ly to use the full 4k main monitor even though I have a smaller side monitor as well.

Seems like the smallest monitor's size is used to set the TTY frame buffer size (which is being mirrored on all displays). That is why you see Ly (or the console for that matter) taking up only a portion of your larger screen starting from top left.

I've fixed it on my Debian bookworm with a systemd service to resize the frame buffer just before Ly starts:

```
$ cat /etc/systemd/system/fbset.service
[Unit]
Description=Framebuffer resolution
Before=display-manager.service

[Service]
Type=oneshot
User=root
ExecStart=/usr/bin/fbset -xres 3840 -yres 2160 -match --all
RemainAfterExit=yes
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
```
Don't forget to `systemctl daemon-reload` and `systemctl enable fbset`. I was also missing the util itself so had to `apt install fbset`.


Linking #366 here  for reference

**Comment by tedkaczynski-dev** [comment]
@Tadas Thank you! This fixed it for me on Arch. I have a monitor connected through an adapter which I suspect is constantly reporting itself as even when it's turned off as Ly, Lemurs, and Greetd were getting resized on my main monitor. Now Ly is perfectly centered, this did the trick.

**Comment by lpv11** [comment]
> Not sure if there are several different issues causing problems for everyone here, but here's how I've gotten Ly to use the full 4k main monitor even though I have a smaller side monitor as well.
> 
> Seems like the smallest monitor's size is used to set the TTY frame buffer size (which is being mirrored on all displays). That is why you see Ly (or the console for that matter) taking up only a portion of your larger screen starting from top left.
> 
> I've fixed it on my Debian bookworm with a systemd service to resize the frame buffer just before Ly starts:
> 
> ```
> $ cat /etc/systemd/system/fbset.service
> [Unit]
> Description=Framebuffer resolution
> Before=display-manager.service
> 
> [Service]
> Type=oneshot
> User=root
> ExecStart=/usr/bin/fbset -xres 3840 -yres 2160 -match --all
> RemainAfterExit=yes
> StandardOutput=journal
> StandardError=journal
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Don't forget to `systemctl daemon-reload` and `systemctl enable fbset`. I was also missing the util itself so had to `apt install fbset`.
> 
> Linking [#366](https://github.com/fairyglade/ly/issues/366) here for reference
I have a 1440p main and a 1080p side monitor, I have adjusted the resolution in the service file accordingly but it still fails to start. In terminal it works fine. Any idea why it might be happening?
`Feb 26 21:39:52 lp-linux fbset[632]: open /dev/fb0: No such file or directory
Feb 26 21:39:51 lp-linux systemd[1]: Starting Framebuffer resolution...
Feb 26 21:39:51 lp-linux systemd[1]: fbset.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 21:39:51 lp-linux systemd[1]: fbset.service: Failed with result 'exit-code'.
Feb 26 21:39:51 lp-linux systemd[1]: Failed to start Framebuffer resolution.`

**Comment by lpv11** [comment]
> > Not sure if there are several different issues causing problems for everyone here, but here's how I've gotten Ly to use the full 4k main monitor even though I have a smaller side monitor as well.
> > Seems like the smallest monitor's size is used to set the TTY frame buffer size (which is being mirrored on all displays). That is why you see Ly (or the console for that matter) taking up only a portion of your larger screen starting from top left.
> > I've fixed it on my Debian bookworm with a systemd service to resize the frame buffer just before Ly starts:
> > ```
> > $ cat /etc/systemd/system/fbset.service
> > [Unit]
> > Description=Framebuffer resolution
> > Before=display-manager.service
> > 
> > [Service]
> > Type=oneshot
> > User=root
> > ExecStart=/usr/bin/fbset -xres 3840 -yres 2160 -match --all
> > RemainAfterExit=yes
> > StandardOutput=journal
> > StandardError=journal
> > 
> > [Install]
> > WantedBy=multi-user.target
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Don't forget to `systemctl daemon-reload` and `systemctl enable fbset`. I was also missing the util itself so had to `apt install fbset`.
> > Linking [#366](https://github.com/fairyglade/ly/issues/366) here for reference
> > I have a 1440p main and a 1080p side monitor, I have adjusted the resolution in the service file accordingly but it still fails to start. In terminal it works fine. Any idea why it might be happening?
> > ```Feb 26 21:39:52 lp-linux fbset[632]: open /dev/fb0: No such file or directory Feb 26 21:39:51 lp-linux systemd[1]: Starting Framebuffer resolution... Feb 26 21:39:51 lp-linux systemd[1]: fbset.service: Main process exited, code=exited, status=1/FAILURE Feb 26 21:39:51 lp-linux systemd[1]: fbset.service: Failed with result 'exit-code'. Feb 26 21:39:51 lp-linux systemd[1]: Failed to start Framebuffer resolution.```

**Comment by g0pher0** [comment]
Does anyone else have the issue where @Tadas' fix centers the higher resolution monitor, but ends up shifting the login box down and to the right on the lower resolution one?

**Comment by RoccoRakete** [comment]
I haven't had this issue for a while. But today, out of nowhere it started happening again.
